### ISSUE TITLE
Not supported A4000

### ISSUE THREAD

**Issue by Boymerkz** [Cyberes/xformers-compiled#2]
ERROR: paperspce-a4000-xformers-0.0.14.dev0-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.

Paperspace - python 3.9

**Comment by Boymerkz** [comment]
Upgrading pip to 22.3 

root@ngtfky91c0:/notebooks# pip install paperspce-a4000-xformers-0.0.14.dev0-cp39-cp39-linux_x86_64.whl
ERROR: paperspce-a4000-xformers-0.0.14.dev0-cp39-cp39-linux_x86_64.whl is not a valid wheel filename.

**Comment by Cyberes** [comment]
Fixed. Update your notebook please.
