### ISSUE TITLE
A4000 failing to install still

### ISSUE THREAD

**Issue by Boymerkz** [Cyberes/xformers-compiled#3]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradient-utils 0.5.0 requires wheel<0.36.0,>=0.35.1, but you have wheel 0.37.1 which is incompatible.

pip install wheel==0.35.1 - Fails to work.

**Comment by Boymerkz** [comment]
test
Steps: 50, Sampler: Euler a, CFG scale: 7, Seed: 2167965404, Size: 512x512, Model hash: 3e16efc8
Time taken: 37.18s Torch active/reserved: 1730/2562 MiB, Sys VRAM: 3860/16118 MiB (23.95%)

It's resulting in 50 steps ( no highres ) taking 37 seconds with this wheel installed and only 12 seconds without it

**Comment by Boymerkz** [comment]
I use you book daily so i don't mind testing stuff with each update ( discord - Creative Digitals#7215 ) 
Is it possible to build a dockerhub container with all the relevant stuff installed then the only the pip install wheel command needs to be done,

**Comment by Boymerkz** [comment]
I use you book daily so i don't mind testing stuff with each update ( discord - Creative Digitals#7215 )
Is it possible to build a dockerhub container with all the relevant stuff installed then the only the pip install wheel command needs to be done,

!python webui.py {x_arg} {dd_arg} --gradio-debug --share # --gradio-auth me:password1234 ( --medvram ) was the issue with it slowing down, would it be worth # --medvram by default with the option to uncomment it, 

everything is now working as it should

**Comment by corytaitchison** [comment]
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. gradient-utils 0.5.0 requires wheel<0.36.0,>=0.35.1, but you have wheel 0.37.1 which is incompatible.
> 
> pip install wheel==0.35.1 - Fails to work.

Hey, how did you manage to fix this? I'm still getting that error on an A4000.

**Comment by Cyberes** [comment]
I've noticed this error but it doesn't seem to effect anything and the process succeeds. It's just packages complaining about their ideal dependency version not being installed.
